- name: create postgres data dir
  file: path=/opt/data/postgres state=directory
- name: create postgres container
  docker_container:
    name: postgres
    image: postgres:9.6
    restart_policy: always
    volumes:
      - /opt/data/postgres:/var/lib/postgresql/data
    env:
      POSTGRES_USER: "{{ db_user }}"
      POSTGRES_PASSWORD: "{{ db_password }}"
      POSTGRES_DB: "{{ db_name }}"
    ports:
      - 5432:5432
    networks:
      - name: "{{ network_name }}"
